trigger:
- main

pool: Default

steps:
- task: Bash@3
- script: |
    npm install
  displayName: 'npm install'

- script: |
    npm run build
  displayName: 'npm build'

- script: |
    echo $spwd | sudo -S cp -R build /var/www/trygven.no/html/
    echo $spwd | sudo -s nginx -s reload
  displayName: 'copy files and reload nginx'
  env:
    spwd: $(spwd) 