trigger:
- main

pool: Default

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
    echo $spwd | sudo -S cp -R build /var/www/trygven.no/html/
    echo $spwd | sudo -s nginx -s reload
  displayName: 'npm install, build and release'
  env:
    spwd: $(spwd) 
